// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.googlecode.cxf.protobuf.addressbook;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Person extends
      com.google.protobuf.GeneratedMessage {
    // Use Person.newBuilder() to construct.
    private Person() {}
    
    private static final Person defaultInstance = new Person();
    public static Person getDefaultInstance() {
      return defaultInstance;
    }
    
    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_Person_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_Person_fieldAccessorTable;
    }
    
    public static enum PhoneType {
      MOBILE(0, 0),
      HOME(1, 1),
      WORK(2, 2),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final PhoneType[] VALUES = {
        MOBILE, HOME, WORK, 
      };
      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.getDescriptor();
      }
    }
    
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessage {
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber() {}
      
      private static final PhoneNumber defaultInstance = new PhoneNumber();
      public static PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }
      
      public PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_Person_PhoneNumber_descriptor;
      }
      
      @Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_Person_PhoneNumber_fieldAccessorTable;
      }
      
      // required string number = 1;
      private boolean hasNumber;
      private java.lang.String number_ = "";
      public boolean hasNumber() { return hasNumber; }
      public java.lang.String getNumber() { return number_; }
      
      // optional .tutorial.Person.PhoneType type = 2 [default = HOME];
      private boolean hasType;
      private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneType type_ = com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneType.HOME;
      public boolean hasType() { return hasType; }
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneType getType() { return type_; }
      
      public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return new Builder(); }
      public static Builder newBuilder(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber prototype) {
        return new Builder().mergeFrom(prototype);
      }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        // Construct using com.example.tutorial.AddressBookProtos.Person.PhoneNumber.newBuilder()
        private Builder() {}
        
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber();
        
        @Override
        protected com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber internalGetResult() {
          return result;
        }
        
        @Override
        public Builder clear() {
          result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber();
          return this;
        }
        
        @Override
        public Builder clone() {
          return new Builder().mergeFrom(result);
        }
        
        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber.getDescriptor();
        }
        
        public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber getDefaultInstanceForType() {
          return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber.getDefaultInstance();
        }
        
        public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber build() {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result);
          }
          return buildPartial();
        }
        
        private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber buildPartial() {
          com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber returnMe = result;
          result = null;
          return returnMe;
        }
        
        
        // required string number = 1;
        public boolean hasNumber() {
          return result.hasNumber();
        }
        public java.lang.String getNumber() {
          return result.getNumber();
        }
        public Builder setNumber(java.lang.String value) {
          result.hasNumber = true;
          result.number_ = value;
          return this;
        }
        public Builder clearNumber() {
          result.hasNumber = false;
          result.number_ = "";
          return this;
        }
        
        // optional .tutorial.Person.PhoneType type = 2 [default = HOME];
        public boolean hasType() {
          return result.hasType();
        }
        public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneType getType() {
          return result.getType();
        }
        public Builder setType(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneType value) {
          result.hasType = true;
          result.type_ = value;
          return this;
        }
        public Builder clearType() {
          result.hasType = false;
          result.type_ = com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneType.HOME;
          return this;
        }
      }
      
      static {
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.getDescriptor();
      }
    }
    
    // required string name = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required int32 id = 2;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string email = 3;
    private boolean hasEmail;
    private java.lang.String email_ = "";
    public boolean hasEmail() { return hasEmail; }
    public java.lang.String getEmail() { return email_; }
    
    // repeated .tutorial.Person.PhoneNumber phone = 4;
    private java.util.List<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber> phone_ =
      java.util.Collections.emptyList();
    public java.util.List<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber> getPhoneList() {
      return phone_;
    }
    public int getPhoneCount() { return phone_.size(); }
    public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.example.tutorial.AddressBookProtos.Person.newBuilder()
      private Builder() {}
      
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person();
      
      @Override
      protected com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.getDescriptor();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person getDefaultInstanceForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.getDefaultInstance();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person buildPartial() {
        if (result.phone_ != java.util.Collections.EMPTY_LIST) {
          result.phone_ =
            java.util.Collections.unmodifiableList(result.phone_);
        }
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // required int32 id = 2;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string email = 3;
      public boolean hasEmail() {
        return result.hasEmail();
      }
      public java.lang.String getEmail() {
        return result.getEmail();
      }
      public Builder setEmail(java.lang.String value) {
        result.hasEmail = true;
        result.email_ = value;
        return this;
      }
      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = "";
        return this;
      }
      
      // repeated .tutorial.Person.PhoneNumber phone = 4;
      public java.util.List<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber> getPhoneList() {
        return java.util.Collections.unmodifiableList(result.phone_);
      }
      public int getPhoneCount() {
        return result.getPhoneCount();
      }
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber getPhone(int index) {
        return result.getPhone(index);
      }
      public Builder setPhone(int index, com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber value) {
        result.phone_.set(index, value);
        return this;
      }
      public Builder setPhone(int index, com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
        result.phone_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPhone(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber value) {
        if (result.phone_.isEmpty()) {
          result.phone_ = new java.util.ArrayList<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber>();
        }
        result.phone_.add(value);
        return this;
      }
      public Builder addPhone(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
        if (result.phone_.isEmpty()) {
          result.phone_ = new java.util.ArrayList<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber>();
        }
        result.phone_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPhone(
          java.lang.Iterable<? extends com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber> values) {
        if (result.phone_.isEmpty()) {
          result.phone_ = new java.util.ArrayList<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber>();
        }
        super.addAll(values, result.phone_);
        return this;
      }
      public Builder clearPhone() {
        result.phone_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.getDescriptor();
    }
  }
  
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessage {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook() {}
    
    private static final AddressBook defaultInstance = new AddressBook();
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_AddressBook_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_AddressBook_fieldAccessorTable;
    }
    
    // repeated .tutorial.Person person = 1;
    private java.util.List<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person> person_ =
      java.util.Collections.emptyList();
    public java.util.List<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person> getPersonList() {
      return person_;
    }
    public int getPersonCount() { return person_.size(); }
    public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person getPerson(int index) {
      return person_.get(index);
    }
    
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.example.tutorial.AddressBookProtos.AddressBook.newBuilder()
      private Builder() {}
      
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook();
      
      @Override
      protected com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook.getDescriptor();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook getDefaultInstanceForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook.getDefaultInstance();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook buildPartial() {
        if (result.person_ != java.util.Collections.EMPTY_LIST) {
          result.person_ =
            java.util.Collections.unmodifiableList(result.person_);
        }
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .tutorial.Person person = 1;
      public java.util.List<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person> getPersonList() {
        return java.util.Collections.unmodifiableList(result.person_);
      }
      public int getPersonCount() {
        return result.getPersonCount();
      }
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person getPerson(int index) {
        return result.getPerson(index);
      }
      public Builder setPerson(int index, com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person value) {
        result.person_.set(index, value);
        return this;
      }
      public Builder setPerson(int index, com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.Builder builderForValue) {
        result.person_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPerson(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person value) {
        if (result.person_.isEmpty()) {
          result.person_ = new java.util.ArrayList<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person>();
        }
        result.person_.add(value);
        return this;
      }
      public Builder addPerson(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.Builder builderForValue) {
        if (result.person_.isEmpty()) {
          result.person_ = new java.util.ArrayList<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person>();
        }
        result.person_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPerson(
          java.lang.Iterable<? extends com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person> values) {
        if (result.person_.isEmpty()) {
          result.person_ = new java.util.ArrayList<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person>();
        }
        super.addAll(values, result.person_);
        return this;
      }
      public Builder clearPerson() {
        result.person_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.getDescriptor();
    }
  }
  
  public static final class AddressBookServiceMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use AddressBookServiceMessage.newBuilder() to construct.
    private AddressBookServiceMessage() {}
    
    private static final AddressBookServiceMessage defaultInstance = new AddressBookServiceMessage();
    public static AddressBookServiceMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressBookServiceMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_AddressBookServiceMessage_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_AddressBookServiceMessage_fieldAccessorTable;
    }
    
    // optional .tutorial.Person addPerson = 1;
    private boolean hasAddPerson;
    private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person addPerson_ = com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.getDefaultInstance();
    public boolean hasAddPerson() { return hasAddPerson; }
    public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person getAddPerson() { return addPerson_; }
    
    // optional .tutorial.NamePattern listPeople = 2;
    private boolean hasListPeople;
    private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern listPeople_ = com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.getDefaultInstance();
    public boolean hasListPeople() { return hasListPeople; }
    public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern getListPeople() { return listPeople_; }
    
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.example.tutorial.AddressBookProtos.AddressBookServiceMessage.newBuilder()
      private Builder() {}
      
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage();
      
      @Override
      protected com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage.getDescriptor();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage getDefaultInstanceForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage.getDefaultInstance();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage buildPartial() {
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional .tutorial.Person addPerson = 1;
      public boolean hasAddPerson() {
        return result.hasAddPerson();
      }
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person getAddPerson() {
        return result.getAddPerson();
      }
      public Builder setAddPerson(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person value) {
        result.hasAddPerson = true;
        result.addPerson_ = value;
        return this;
      }
      public Builder setAddPerson(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.Builder builderForValue) {
        result.hasAddPerson = true;
        result.addPerson_ = builderForValue.build();
        return this;
      }
      public Builder mergeAddPerson(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person value) {
        if (result.hasAddPerson() &&
            result.addPerson_ != com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.getDefaultInstance()) {
          result.addPerson_ =
            com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.newBuilder(result.addPerson_).mergeFrom(value).buildPartial();
        } else {
          result.addPerson_ = value;
        }
        result.hasAddPerson = true;
        return this;
      }
      public Builder clearAddPerson() {
        result.hasAddPerson = false;
        result.addPerson_ = com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.getDefaultInstance();
        return this;
      }
      
      // optional .tutorial.NamePattern listPeople = 2;
      public boolean hasListPeople() {
        return result.hasListPeople();
      }
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern getListPeople() {
        return result.getListPeople();
      }
      public Builder setListPeople(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern value) {
        result.hasListPeople = true;
        result.listPeople_ = value;
        return this;
      }
      public Builder setListPeople(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.Builder builderForValue) {
        result.hasListPeople = true;
        result.listPeople_ = builderForValue.build();
        return this;
      }
      public Builder mergeListPeople(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern value) {
        if (result.hasListPeople() &&
            result.listPeople_ != com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.getDefaultInstance()) {
          result.listPeople_ =
            com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.newBuilder(result.listPeople_).mergeFrom(value).buildPartial();
        } else {
          result.listPeople_ = value;
        }
        result.hasListPeople = true;
        return this;
      }
      public Builder clearListPeople() {
        result.hasListPeople = false;
        result.listPeople_ = com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.getDefaultInstance();
        return this;
      }
    }
    
    static {
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.getDescriptor();
    }
  }
  
  public static final class AddressBookSize extends
      com.google.protobuf.GeneratedMessage {
    // Use AddressBookSize.newBuilder() to construct.
    private AddressBookSize() {}
    
    private static final AddressBookSize defaultInstance = new AddressBookSize();
    public static AddressBookSize getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressBookSize getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_AddressBookSize_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_AddressBookSize_fieldAccessorTable;
    }
    
    // optional int32 size = 1;
    private boolean hasSize;
    private int size_ = 0;
    public boolean hasSize() { return hasSize; }
    public int getSize() { return size_; }
    
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.example.tutorial.AddressBookProtos.AddressBookSize.newBuilder()
      private Builder() {}
      
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize();
      
      @Override
      protected com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize.getDescriptor();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize getDefaultInstanceForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize.getDefaultInstance();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize buildPartial() {
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional int32 size = 1;
      public boolean hasSize() {
        return result.hasSize();
      }
      public int getSize() {
        return result.getSize();
      }
      public Builder setSize(int value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0;
        return this;
      }
    }
    
    static {
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.getDescriptor();
    }
  }
  
  public static final class NamePattern extends
      com.google.protobuf.GeneratedMessage {
    // Use NamePattern.newBuilder() to construct.
    private NamePattern() {}
    
    private static final NamePattern defaultInstance = new NamePattern();
    public static NamePattern getDefaultInstance() {
      return defaultInstance;
    }
    
    public NamePattern getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_NamePattern_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.internal_static_tutorial_NamePattern_fieldAccessorTable;
    }
    
    // optional string pattern = 1;
    private boolean hasPattern;
    private java.lang.String pattern_ = "";
    public boolean hasPattern() { return hasPattern; }
    public java.lang.String getPattern() { return pattern_; }
    
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.example.tutorial.AddressBookProtos.NamePattern.newBuilder()
      private Builder() {}
      
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern();
      
      @Override
      protected com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.getDescriptor();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern getDefaultInstanceForType() {
        return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.getDefaultInstance();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern buildPartial() {
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string pattern = 1;
      public boolean hasPattern() {
        return result.hasPattern();
      }
      public java.lang.String getPattern() {
        return result.getPattern();
      }
      public Builder setPattern(java.lang.String value) {
        result.hasPattern = true;
        result.pattern_ = value;
        return this;
      }
      public Builder clearPattern() {
        result.hasPattern = false;
        result.pattern_ = "";
        return this;
      }
    }
    
    static {
      com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.getDescriptor();
    }
  }
  
  public static abstract class AddressBookService
      implements com.google.protobuf.Service {
    public abstract void addPerson(
        com.google.protobuf.RpcController controller,
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person request,
        com.google.protobuf.RpcCallback<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize> done);
    public abstract void listPeople(
        com.google.protobuf.RpcController controller,
        com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern request,
        com.google.protobuf.RpcCallback<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.addPerson(controller, (com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person)request,
            com.google.protobuf.RpcUtil.<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize>specializeCallback(
              done));
          return;
        case 1:
          this.listPeople(controller, (com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern)request,
            com.google.protobuf.RpcUtil.<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.RuntimeException("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.getDefaultInstance();
        case 1:
          return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.getDefaultInstance();
        default:
          throw new java.lang.RuntimeException("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize.getDefaultInstance();
        case 1:
          return com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook.getDefaultInstance();
        default:
          throw new java.lang.RuntimeException("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookService {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public void addPerson(
          com.google.protobuf.RpcController controller,
          com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person request,
          com.google.protobuf.RpcCallback<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize.class,
            com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize.getDefaultInstance()));
      }
      
      public void listPeople(
          com.google.protobuf.RpcController controller,
          com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern request,
          com.google.protobuf.RpcCallback<com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook.class,
            com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook.getDefaultInstance()));
      }
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Person_PhoneNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Person_PhoneNumber_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_AddressBook_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressBookServiceMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_AddressBookServiceMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressBookSize_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_AddressBookSize_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_NamePattern_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_NamePattern_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\021addressbook.proto\022\010tutorial\"\332\001\n\006Person" +
      "\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005email\030\003 \001(" +
      "\t\022+\n\005phone\030\004 \003(\0132\034.tutorial.Person.Phone" +
      "Number\032M\n\013PhoneNumber\022\016\n\006number\030\001 \002(\t\022.\n" +
      "\004type\030\002 \001(\0162\032.tutorial.Person.PhoneType:" +
      "\004HOME\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001" +
      "\022\010\n\004WORK\020\002\"/\n\013AddressBook\022 \n\006person\030\001 \003(" +
      "\0132\020.tutorial.Person\"k\n\031AddressBookServic" +
      "eMessage\022#\n\taddPerson\030\001 \001(\0132\020.tutorial.P" +
      "erson\022)\n\nlistPeople\030\002 \001(\0132\025.tutorial.Nam" +
      "ePattern\"\037\n\017AddressBookSize\022\014\n\004size\030\001 \001(" +
      "\005\"\036\n\013NamePattern\022\017\n\007pattern\030\001 \001(\t2\212\001\n\022Ad" +
      "dressBookService\0228\n\taddPerson\022\020.tutorial" +
      ".Person\032\031.tutorial.AddressBookSize\022:\n\nli" +
      "stPeople\022\025.tutorial.NamePattern\032\025.tutori" +
      "al.AddressBookB)\n\024com.example.tutorialB\021" +
      "AddressBookProtos";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Person_descriptor,
              new java.lang.String[] { "Name", "Id", "Email", "Phone", },
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.class,
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.Builder.class);
          internal_static_tutorial_Person_PhoneNumber_descriptor =
            internal_static_tutorial_Person_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_Person_PhoneNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Person_PhoneNumber_descriptor,
              new java.lang.String[] { "Number", "Type", },
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber.class,
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.Person.PhoneNumber.Builder.class);
          internal_static_tutorial_AddressBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_AddressBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_AddressBook_descriptor,
              new java.lang.String[] { "Person", },
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook.class,
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBook.Builder.class);
          internal_static_tutorial_AddressBookServiceMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_tutorial_AddressBookServiceMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_AddressBookServiceMessage_descriptor,
              new java.lang.String[] { "AddPerson", "ListPeople", },
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage.class,
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookServiceMessage.Builder.class);
          internal_static_tutorial_AddressBookSize_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_tutorial_AddressBookSize_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_AddressBookSize_descriptor,
              new java.lang.String[] { "Size", },
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize.class,
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.AddressBookSize.Builder.class);
          internal_static_tutorial_NamePattern_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_tutorial_NamePattern_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_NamePattern_descriptor,
              new java.lang.String[] { "Pattern", },
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.class,
              com.googlecode.cxf.protobuf.addressbook.AddressBookProtos.NamePattern.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
